version: "3.9"
services:
  app:
    build: .
    container_name: pyweb-template
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - ENV=DOCKER
