framework: fastapi
#framework: flask

app:
  name: "Py Multi Mode App Template"
  version: "1.0.0"
  debug: true
  port: 5000

constants:
  greeting_message: "Hello, user!"
  post_ack: "Data received successfully."

logging:
  level: "INFO"

llm_config:
  provider: "openai" # or "ollama"
  model: "gpt-4o" # or "llama3"
  temperature: 0.7
  context_window: 1000
  include_history: true
  history_length: 10
